### ISSUE TITLE
Stimulus class: ConcatenatedInput and SummedInput

### ISSUE THREAD

**Issue by caglorithm** [neurolib-dev/neurolib#150]
* SummedInput should sum two stimuli with `+` operator
* ConcatenatedInput should concatenate stimuli with `&` operator

**Comment by jajcayn** [comment]
### `ConcatenatedInput` conundrum 
I started implementing this, but with concatenation, there is a problem. All `ModelInput` classes are created on init but the time series are actually created when calling either `as_array(duration, dt)` or `as_cubic_splines(duration, dt)`.

E.g.
```python
ou = OrnsteinUhlenbeckProcess(mu=0.1, sigma=0.02, tau=2.0)
sq = SquareInput(amplitude=0.2, period=20.0, stim_start=5)
```

now, you can easily do `ou + sq` which gives you `SummedInput` and then, when you actually need the time series you do `(ou  + sq).as_array(duration, dt)`

with `ConcatenatedInput` I cannot imagine how it should work... `ou & sq` would give you this but then `(ou & sq).as_array(duration, dt)` would give you what? duration is split into 2 and the first half is `ou`, the second half is `sq`? That will work, but what if you want only the first 1/4 of the total duration to have `ou`, and then the remaining 3/4 should be `sq`?

the class itself can have this with e.g.
```python
class SummedInput(StimulusInput):

    def __init__(self, processes, length_ratios):
```
and in the above case, you would do `length_ratios=[1,3]`... easy...
BUT, there is no way how to do this with AND operator... so the class can accommodate concatenation easily, but `ou & sq` mechanism can only do the same ratios... So we can do it like this:
- if you want the same length ratios, you can use `&` operator, which automatically creates `length_ratios = [1] * len(processes)`
- if you want different length ratios, you need to use class init with `ConcatenatedInput([ou, sq], [1, 3])`

What do you say?

### Interaction of `ConcatenatedInput` and `SummedInput`
Because why not?
Anyway, the real question is the order of operations. 
Imagine this:
```python
ou = OrnsteinUhlenbeckProcess(mu=0.1, sigma=0.02, tau=2.0)
sq = SquareInput(amplitude=0.2, period=20.0)
sin = SinusoidalInput(amplitude=0.1, period=10.0)
step = StepInput(step_size=0.5)

final = ou + sq & sin + step
```
the question is, do we want default pythonic order, i.e.:
1. `ou + sq` will create summed input of these two
2. `(ou + sq) & sin` will create an input with the first half being a sum of `sq` and `ou` and the second half being the `sin`
3. finally a `step` will be added (+) to the above input

or should `+` be given a priority so that
1. `ou + sq` will create summed input of these two
2. `sin + step` will create a summed input of these two
3. finally, the first half of the concatenated input will be `ou + sq` and the second half will be `sin + step`

For the first option, there is no additional work that has to be done (this should be python default if I am not mistaken).. However, the second option makes more sense to me, but it'll be tricky to implement..

**Comment by jajcayn** [comment]
Actually sorry, for the second thing (Interaction of `ConcatenatedInput` and `SummedInput`) - forget about it... I think we will do the first option - default pythonic because we can still use brackets...
```python
# first ou + sq; then concat with sin; AND THEN + step
final = ou + sq & sin + step

# first sum ou and sq, and sin + step; THEN concat these two summed
final = (ou + sq) & (sin + step)
```

easy and elegant... so only the first question still hangs...
