### ISSUE TITLE
pypet PicklingError 

### ISSUE THREAD

**Issue by vagechirkov** [neurolib-dev/neurolib#154]
Dear all,

I've tried to reproduce the following example:

```Python

from neurolib.models.aln import ALNModel
from neurolib.optimize.exploration import BoxSearch
from neurolib.utils.parameterSpace import ParameterSpace

model = ALNModel()
parameters = ParameterSpace({"mue_ext_mean": np.linspace(0, 3, 21),
                             "mui_ext_mean": np.linspace(0, 3, 21)})

search = BoxSearch(model, parameters)
search.run()
search.loadResults()

```

#### Error

in the line `search.run()` I have the following error:

<details>

```bash
Exception has occurred: PicklingError
Can't pickle <class 'neurolib.utils.parameterSpace.ParameterSpace'>: it's not the same object as neurolib.utils.parameterSpace.ParameterSpace
  File "/neurolib/optimize/exploration/exploration.py", line 281, in run self.env.run(self.evalFunction)
```

</details>

#### Environment

<details>

![image](https://user-images.githubusercontent.com/42982039/116928402-4f75fa80-ac5d-11eb-9274-fa086e44478f.png)

</details>

#### Solution

After some trials and errors, I've changed `multiproc=True` to `multiproc=False` [here](https://github.com/neurolib-dev/neurolib/blob/a42575d1dc0f6cac6bdf00682902ccd7eef7cb34/neurolib/optimize/exploration/exploration.py#L101) and everything works fine.

Looking forward to your comments!

Valerii

**Comment by jajcayn** [comment]
Dear Valerii,

Thanks for your interest in neurolib!
Unfortunately, due to some breaking changes related to forking a process, python3.8 is not currently supported on macOS systems. Our dependency on the `pypet` package and its multiprocessing scheme is the culprit. We thought of migrating for some different solutions, but for now, please use a lower version of Python. Pythons 3.6 and 3.7 are tested regularly and working as they should on MacOS. Myself, I am running 11.3 and python 3.7.10 for development. 

Just as a good measure, I successfully ran the code you posted with python 3.7.10 with a fresh install of neurolib in a temporary virtual environment:
<img width="1278" alt="Screenshot 2021-05-04 at 12 26 49 AM" src="https://user-images.githubusercontent.com/6525217/116941189-83f2b200-ac6f-11eb-97dd-8f4ecb3212af.png">
<img width="1104" alt="Screenshot 2021-05-04 at 12 26 57 AM" src="https://user-images.githubusercontent.com/6525217/116941193-86550c00-ac6f-11eb-8882-3225079f2655.png">


I hope this intermediate solution works for you and you are able to accommodate python 3.7 for now :)

Thanks again and happy brain simulating!

**Comment by vagechirkov** [comment]
Dear @jajcayn,

Thank you for your quick reply and your help! 

I've changed python to 3.7.10, and everything works fine, although I've noticed that with `multiproc=False` it works much faster. Maybe this is because I am using Apple M1...

**Comment by jajcayn** [comment]
Hey,

no problem, glad to help:)
Well, yes. For this particular use case, the single processing will always be faster, since one simulation of the ALN 1 node model for 2seconds can be done in a tiny fraction of a second, and then the overhead caused by forking a process and then waiting for them to synchronize is much much larger than the simulation itself. The more complex the model is (therefore, the more a single simulation would take), the more multiprocessing makes sense.

You can try to do the same thing with the brain network instead of one node, e.g. do something like:
```python
# make 20-node brain network
model = ALNModel(Cmat=np.random.rand(20,20))
# simulate for one minute
model.params["duration"] = 60.0 * 1e3 # in ms
```
to create a brain network with 20 nodes, connected randomly. Now the simulation of a single time will be significantly longer, and you'll benefit from multiprocessing on exploration. In general, multiprocessing always comes with an overhead of forking a process and waiting for them to sync, so it is not always the best option to use it.

By the way, I am also using an M1 machine and instead of the non-existing `gcc` for arm64, I didn't encounter any problems so far:) 

Best,
N.

**Comment by vagechirkov** [comment]
> Hey,
> 
> no problem, glad to help:)
> Well, yes. For this particular use case, the single processing will always be faster, since one simulation of the ALN 1 node model for 2seconds can be done in a tiny fraction of a second, and then the overhead caused by forking a process and then waiting for them to synchronize is much much larger than the simulation itself. The more complex the model is (therefore, the more a single simulation would take), the more multiprocessing makes sense.
> 
> You can try to do the same thing with the brain network instead of one node, e.g. do something like:
> 
> ```python
> # make 20-node brain network
> model = ALNModel(Cmat=np.random.rand(20,20))
> # simulate for one minute
> model.params["duration"] = 60.0 * 1e3 # in ms
> ```
> 
> to create a brain network with 20 nodes, connected randomly. Now the simulation of a single time will be significantly longer, and you'll benefit from multiprocessing on exploration. In general, multiprocessing always comes with an overhead of forking a process and waiting for them to sync, so it is not always the best option to use it.
> 
> By the way, I am also using an M1 machine and instead of the non-existing `gcc` for arm64, I didn't encounter any problems so far:)
> 
> Best,
> N.

Alright! Thank you very much for the explanation! 

I think I will close the issue because everything works fine on my computer.

Thank you for your help!
