### ISSUE TITLE
neurolib docker

### ISSUE THREAD

**Issue by jajcayn** [neurolib-dev/neurolib#167]
What do you think of creating a docker file with neurolib preinstalled?
There would be a couple of advantages: very easy install, can be run anywhere (Windows without problems), etc...
I can imagine some people not so comfortable with setting up the whole python environment, but ok enough with docker.

**Comment by caglorithm** [comment]
I agree it would make it easier to install for _some_ people but I don't see how it is harder to install using `pip` oder clone the repo. I think docker is excellent for exact reproduction of a pipeline but I think at least I haven't experienced any situation where I thought a docker image would have helped. It would also add to the maintenance cost which is why I'm slightly off favor for this idea.

Windows users have much bigger fish to fry ;) (Docker wouldn't help a naive Windows user, because they don't use Docker / could install a virtual machine or linux subsystem, if they are more advanced :)

**Comment by jajcayn** [comment]
all valid points... I guess the disadvantages overweight possible advantages, hence not going to follow up on this; closing
