### ISSUE TITLE
ALNModel.run(append_outputs=True) works only for default outputs

### ISSUE THREAD

**Issue by vagechirkov** [neurolib-dev/neurolib#175]
Hi, I have tried to store additional outputs ("mufe", "mufi", "seem" etc.) as timeseries for the ALN model.
Here is an example and output:

<details>

Example:
```python

from neurolib.utils.loadData import Dataset
from neurolib.models.aln import ALNModel
ds = Dataset("gw")
model = ALNModel(Cmat=ds.Cmat, Dmat=ds.Dmat)
model.output_vars += model.state_vars
model.run(append_outputs=True)
for key, val in model.outputs.items():
    print(f"{key} {val.shape}")
```

Output:

```bash
t (20000,)
rates_exc (80, 20000)
rates_inh (80, 20000)
mufe (0,)
mufi (0,)
IA (80, 20000)
seem (0,)
seim (0,)
siem (0,)
siim (0,)
seev (0,)
seiv (0,)
siev (0,)
siiv (0,)
mue_ou (0,)
mui_ou (0,)

```

</details>

However, I was able to export timeseries of the variables that I am interested in by creating a new variable with the shape `(N, startind + len(t))` inside `timeIntegration` [here](https://github.com/neurolib-dev/neurolib/blob/f937746516d5664f065c78b7b1a8e9145042ac62/neurolib/models/aln/timeIntegration.py#L173), updating it in the `timeIntegration_njit_elementwise` and then setting it as an output of the `timeIntegration`.

I think the names for the additional output values could be saved in the [`self.param`](https://github.com/neurolib-dev/neurolib/blob/f937746516d5664f065c78b7b1a8e9145042ac62/neurolib/models/model.py#L267).

**Comment by caglorithm** [comment]
Hi @vagechirkov, sorry for getting back at you at a delay. Do you mean that additional outputs could be specified in `output_vars` in `model.py` of the aln model, so they can be added up accordingly when using `chunkwise=True`? Are you using `append_outputs` without chunkwise?

In any case, If I got it right, I would suggest that, since you modified the model itself by saving additional output variables (this was entirely our intention when coding, so thanks for actually modifying the code :), it would be the best to add these names you your customized model. 

So, if we changed the default output of the model, we would edit the `default_output` list in `model.py` but I guess this is not what you're asking about, right?

**Comment by vagechirkov** [comment]
Hi @caglorithm, actually, my comment was intended to be a bug report. I have expected that setting additional `model.output_vars` and then running the model with `append_outputs=True` should produce additional outputs. So I thought this could be potentially misleading for somebody else.

**Comment by caglorithm** [comment]
I see. However, this won't automatically work since not all variables are integrated (to save memory). This needs to be adjusted manually, before setting the output in `output_vars`. Exactly as you've mentioned here:

> However, I was able to export timeseries of the variables that I am interested in by creating a new variable with the shape (N, startind + len(t)) inside timeIntegration

So I wouldn't classify this as a bug but I'll keep in mind to explain this better at some point and maybe write a short tutorial on how to modify a model such that the variable can be saved, I think it's a fairly usual problem people encounter. Thanks for reporting, very much appreciated! Feel free to let us know when you find more.
