### ISSUE TITLE
Reference  for the empirical data

### ISSUE THREAD

**Issue by Ziaeemehr** [neurolib-dev/neurolib#32]
Many thanks for sharing this,
Where can I find the reference of empirical data for FC? detail fo the experiment.

**Comment by caglorithm** [comment]
Thank you for your comment! The data that we have provided in this package serves only demonstrational purposes and since we haven't published anything with the data yet, I cannot tell you a reference. Therefore, I do not recommend using the data for any publication at this stage. We are currently working on a paper in which the data processing pipeline will be described in detail and wich can be referenced then. 

In short, we have processed all data in our lab using `FSL`. The BOLD activity is recorded during resting state (so no stimulus or task). The two datasets cover different age groups: `hcp` is a set of younger adult (around 20 years old) and `gw` is a set of older adults (around 50). Both datasets are mixed genders. I don't have the details on the scan protocol and the scanner's technical specifications in mind, but both of the datasets use modern MRI hardware.

Out of sheer curiosity, can you tell me more about your scientific background and the work that you are doing? I would love to learn which kind of people are using `neurolib` and what kind of scientific questions they are working on!

Feel free to answer here or contact me via mail if you need more specific information (cakan@ni.tu-berlin.de)!

**Comment by Ziaeemehr** [comment]
OK, I just want to check some of my results,  I am not going to use the data in our preprint without required permissions . I am physics student and I am working on structure dynamics interplay in some artificial and also connectome data. 
regards.
